/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ComedyClash__factory } from "./ComedyClash__factory";
export { ComedyTheater__factory } from "./ComedyTheater__factory";
