/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ComedyClash } from "./ComedyClash";
export type { ComedyTheater } from "./ComedyTheater";
export * as factories from "./factories";
export { ComedyClash__factory } from "./factories/ComedyClash__factory";
export { ComedyTheater__factory } from "./factories/ComedyTheater__factory";
